---

- name: 'Check if Jenkins v2 default administrative password file exists'
  become: True
  stat:
    path: "{{ jenkins_default_adm_passd_file }}"
  register: 'jenkins_administrative_password_file_test'
  changed_when: False 

- name: 'Jenkins 2.0 default password protection workaround'
  include: "{{ role_path }}/tasks/utils/jenkins_password_workaround.yml"
  register: 'jenkins_authentication_disabled'
  when:
    - "jenkins_administrative_password_file_test.stat.exists is defined"
    - "jenkins_administrative_password_file_test.stat.exists" 

- name: restart jenkins
  include: "{{role_path}}/tasks/utils/restart-jenkins.yml"

- name: 'Copy Groovy scripts'
  become: True
  copy:
    src: "{{ role_path }}/files/groovy_scripts"
    dest: "{{ jenkins_etc_home_location }}/"
    owner: "{{ jenkins_etc_user }}"
    group: "{{ jenkins_etc_group }}"
    mode: '0640'  


- include: config-jenkins-docker.yml

- include: config-jenkins-plugin.yml

- name: 'Create job directory'
  file:
    path: /var/lib/jenkins/tmp
    state: directory
    mode: 0755
  become: True

- name: 'Copy config.xml into jenkins jobs folder'
  copy:
    src: "{{ role_path }}/files/config.xml"
    dest: "{{ jenkins_etc_home_location }}/tmp/config.xml"
    owner: "{{ jenkins_etc_user }}"
    group: "{{ jenkins_etc_user }}"
    mode: '0644'
  become: True

- name: 'Create job'
  become: True
  shell: >
          java -jar /var/lib/jenkins/jenkins-cli.jar -auth admin:admin -s http://{{ jenkins_etc_listen_address }}:{{ jenkins_etc_http_port }} create-job demoKafka < {{ jenkins_etc_home_location }}/tmp/config.xml

- name: restart jenkins
  include: "{{role_path}}/tasks/utils/restart-jenkins.yml"  